# Set non-interactive mode for apt and install basic dependencies
FROM nvidia/cuda:12.0.0-devel-ubuntu22.04

LABEL maintainer="azahir@pa.uc3m.es"

# Set bash as default shell, and avoid prompts during package installation
SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      python3 \
      python3-dev \
      python3-pip \
      python3-setuptools && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip first
RUN python3 -m pip install --upgrade pip

# Install torch/torchvision from the CUDA wheels index
RUN pip3 install \
      torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121

RUN pip3 install \
      numpy==1.26.4 \
      pillow==10.4.0 \
      opencv-python-headless==4.10.0.84 \
      flask==3.0.3

# Create a working directory
WORKDIR /app

# Copy your app
COPY app/ .